apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenses-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenses-api
  template:
    metadata:
      labels:
        app: expenses-api
    spec:
      containers:
        - name: expenses-api
          image: hugoejara7/expensesapi:v1
          ports:
            - containerPort: 8080
          
